In [2]:
import numpy as np

In [3]:
A = np.array([[3,1,-2],[1,1,4]])
B = np.array([[0,2,-3],[2,1,0],[1,1,1]])
C = np.array([[4,1,-2],[2,0,0],[-4,0,-1]])
D = np.array([[2,-1],[0,-5],[-1,0]])
np.sum(A @ (B + C) @ D)

-42

In [4]:
A = np.array([[1,5,-2,1],[3,16,-3,11],[0,0,6,10],[-5,-25,10,-1]])
B = np.array([4,19,2,-12])
np.linalg.solve(A, B)

array([-4.00000000e+00,  1.33226763e-15, -3.00000000e+00,  2.00000000e+00])

In [5]:
A = np.array([[1,-2,3],[-3,0,2],[1,-1,4]])
B = np.array([5,2,6])
np.linalg.solve(A, B)

array([ 0.23529412, -0.35294118,  1.35294118])

In [6]:
A = np.array([[0,-2], [4,7]])
B = np.array([1,2])
np.linalg.solve(A, B)

array([ 1.375, -0.5  ])

In [7]:
A = np.array([[3,5,-1], [-4,1,2], [0,1,0]])
np.linalg.inv(A)

array([[  1. ,   0.5,  -5.5],
       [  0. ,   0. ,   1. ],
       [  2. ,   1.5, -11.5]])

In [8]:
A = np.array([[1,1,1,1], [-2,3,2,1], [0,1,1,1], [1,3,1,-2]])
print(np.linalg.inv(A))
np.max(np.linalg.inv(A))

[[ 1.00000000e+00 -0.00000000e+00 -1.00000000e+00  1.11022302e-16]
 [ 7.00000000e+00  3.00000000e+00 -1.20000000e+01 -1.00000000e+00]
 [-1.20000000e+01 -5.00000000e+00  2.10000000e+01  2.00000000e+00]
 [ 5.00000000e+00  2.00000000e+00 -8.00000000e+00 -1.00000000e+00]]


21.0

In [9]:
A = np.array([])
A

array([], dtype=float64)

In [10]:
A = np.array([[1,1,0], [2,1,1], [-1,0,1]])
B = np.array([-1,1,-1])
np.linalg.solve(A, B)

array([ 1.5, -2.5,  0.5])

In [11]:
np.sum(np.linalg.solve(A,B))

-0.5

In [12]:
C = np.array([[1,2,3,-1]])
B = np.array([[1,3,1,0],[1,0,-1,2],[0,0,1,2],[-1,1,0,1]])
C.T @ C @ B.T @ B

array([[  6,  30,  15,  -6],
       [ 12,  60,  30, -12],
       [ 18,  90,  45, -18],
       [ -6, -30, -15,   6]])

In [23]:
from sympy import Matrix, pprint

In [24]:
A = np.array([[1,1,2,-1], [-1,0,3,2], [2,-1,1,0], [0,1,5,1]])
m = Matrix(A).rref()
pprint(m)

⎛⎡1  0  0  -3/4⎤           ⎞
⎜⎢             ⎥           ⎟
⎜⎢         -13 ⎥           ⎟
⎜⎢0  1  0  ────⎥           ⎟
⎜⎢          12 ⎥, (0, 1, 2)⎟
⎜⎢             ⎥           ⎟
⎜⎢0  0  1  5/12⎥           ⎟
⎜⎢             ⎥           ⎟
⎝⎣0  0  0   0  ⎦           ⎠


In [17]:
import scipy.linalg
A = np.array([[-3,4,0], [1,-3,2], [-6,7,1]])
P, L, U = scipy.linalg.lu(A)
print(L)
print("\n")
print(U)

[[ 1.          0.          0.        ]
 [-0.16666667  1.          0.        ]
 [ 0.5        -0.27272727  1.        ]]


[[-6.          7.          1.        ]
 [ 0.         -1.83333333  2.16666667]
 [ 0.          0.          0.09090909]]
