In [40]:
import numpy as np
from scipy.linalg import orth
from sympy import Matrix

In [14]:
B = np.array([[1,0], [-4,5]])
T = np.array([[-1,5], [0,2]])
np.linalg.inv(T) @ B @ T

array([[ 11., -30.],
       [  2.,  -5.]])

In [15]:
B = np.array([[1,-3,1], [-5,0,4], [-7,-5,1]])
T = np.array([[1,3,2], [0,1,-2], [1,4,-1]])
result = np.linalg.inv(T) @ B @ T
print(result)
np.max(np.abs(result))

[[ -51. -215.   65.]
 [  13.   55.  -18.]
 [   7.   27.   -2.]]


215.0

In [16]:
A = np.array([[-4,6], [-3,5]])
v = np.array([2,1])
print(A @ v)
print(np.linalg.eig(A))

[-2 -1]
(array([-1.,  2.]), array([[-0.89442719, -0.70710678],
       [-0.4472136 , -0.70710678]]))


In [17]:
A = np.array([[-1,2,5], [0,4,0], [1,0,3]])
v = np.array([1,0,1])
A @ v

array([4, 0, 4])

In [18]:
A = np.array([[2,1,0], [-1,0,1], [1,3,1]])
w = np.linalg.eigvals(A)
print(w)

[-1.          1.99999998  2.00000002]


In [19]:
A = np.array([[1,0,1], [-2,1,4], [6,-3,8]])
np.linalg.det(A)

19.999999999999996

In [20]:
A = np.array([[-1,-6], [2,6]])
w, v = np.linalg.eig(A)
print(w, v)

[2. 3.] [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


In [21]:
A = np.array([[4,4,0], [-2,-2,0], [2,4,2]])
w, v = np.linalg.eig(A)
print(v)

[[ 0.          0.57735027 -0.89442719]
 [ 0.         -0.57735027  0.4472136 ]
 [ 1.          0.57735027  0.        ]]


In [25]:
A = np.array([[1,2,0], [2,0,2], [0,2,-1]])
v, w = np.linalg.eig(A)
orth(w)

array([[ 0.33333333,  0.66666667, -0.66666667],
       [-0.66666667, -0.33333333, -0.66666667],
       [ 0.66666667, -0.66666667, -0.33333333]])

In [45]:
A = np.array([[0,2], [-3,5]])
w, v = np.linalg.eig(A)
print(v)
zeros = np.zeros(2)
A1 = np.array([[-3,2], [-3,2]])
M1 = Matrix(A1).rref()
print(M1)
A2 = np.array([[-2,2], [-3,3]])
M2 = Matrix(A2).rref()
print(M2)
T = np.array([[1, 2/3], [1, 1]])
print(np.linalg.inv(T))

[[-0.70710678 -0.5547002 ]
 [-0.70710678 -0.83205029]]
(Matrix([
[1, -2/3],
[0,    0]]), (0,))
(Matrix([
[1, -1],
[0,  0]]), (0,))
[[ 3. -2.]
 [-3.  3.]]
