In [5]:
import numpy as np
import math

In [2]:
x = np.array([8,6,4,2,1])
np.linalg.norm(x)

11.0

In [3]:
x = np.array([1,-7,3])
np.linalg.norm(x)

7.681145747868608

In [10]:
x = np.array([1,-3,0])
y = np.array([0,1,-7])
dot_product = np.dot(x, y)
print(dot_product)

-3


In [16]:
x = np.array([3,1,2,5])
y = np.array([-1,4,-3,0])
dot_product = np.dot(x, y)
x_norm = np.linalg.norm(x)
y_norm = np.linalg.norm(y)
result = dot_product / (x_norm * y_norm)
print(result)

-0.15701857325533194


In [17]:
A = np.array([[1,1,1,1],[2,3,0,-1],[1,2,1,3],[1,3,-1,0]])
b = np.zeros(4)
# np.linalg.solve(A, b)

In [18]:
x = np.array([9,-2,4])
y = np.array([2,-5,2])
np.dot(x, y)

36

In [28]:
f1 = np.array([-3,0,2])
f2 = np.array([2,1,2])
f3 = np.array([4,4,-2])
A = np.column_stack((f1, f2, f3))
b = np.zeros(3)
np.linalg.solve(A, b)
x = np.array([-1,2,-1])
A @ x

array([ 3, -2,  4])

In [29]:
e1 = np.array([1,0,1])
e2 = np.array([-1,-1,0])
e3 = np.array([-1,0,3])
T = np.column_stack((e1, e2, e3))
x = np.array([5,-7,8])
np.linalg.inv(T) @ x

array([11.,  7., -1.])

In [30]:
T1 = np.array([[-1,0], [2,-1]])
T2 = np.array([[1,-1], [-3,2]])
T3 = np.linalg.inv(T2) @ T1
x = np.array([2,3])
T3 @ x

array([3., 5.])

In [31]:
a1 = np.array([1,0,1])
a2 = np.array([0,-1,1])
A = np.column_stack((a1, a2))
x = np.array([1,1,2])
A @ np.linalg.inv(A.T @ A) @ A.T @ x

array([1.66666667, 0.33333333, 1.33333333])

In [32]:
a1 = np.array([2,-1,2])
a2 = np.array([1,5,0])
x = np.array([0,-1,5])
A = np.column_stack((a1, a2))
A @ np.linalg.inv(A.T @ A) @ A.T @ x

array([ 2.35555556, -1.47111111,  2.40888889])

In [33]:
a1 = np.array([3,1,0])
a2 = np.array([-5,-7,1])
A = np.column_stack((a1, a2))
b = np.array([0,2,5])
np.linalg.inv(A.T @ A) @ A.T @ b

array([-0.18045113, -0.17293233])

In [36]:
a1 = np.array([-3,1,3,-2])
a2 = np.array([4,3,-2,0])
a3 = np.array([4,2,-3,1])
a4 = np.array([3,-3,-2,3])
A = np.column_stack((a1, a2, a3, a4))
y = np.array([1,2,-1,0])
np.sum(A @ y)

5