In [1]:
import numpy as np

In [5]:
a1 = np.array([1/np.sqrt(11), -1/np.sqrt(11), 3/np.sqrt(11)])
b1 = np.array([1/np.sqrt(2), 1/np.sqrt(2), 0])
print(np.linalg.norm(a1))
print(np.linalg.norm(b1))
print(np.dot(a1, b1))

1.0
0.9999999999999999
-5.45400326236567e-18


In [8]:
a1 = np.array([1,2,0])
a2 = np.array([-1,3,2])
a3 = np.array([0,7,-3])
b1 = a1
b2 = a2 - (np.dot(a2, b1)/np.dot(b1, b1)) * b1
b3 = a3 - (np.dot(a3, b1)/np.dot(b1, b1)) * b1 - (np.dot(a3, b2)/np.dot(b2, b2)) * b2
print(b1, b2, b3)

[1 2 0] [-2.  1.  2.] [-2.57777778  1.28888889 -3.22222222]


In [14]:
a1 = np.array([-1,2,1,0])
a2 = np.array([-1,0,2,-4])
a3 = np.array([3,0,-6,-1])
a4 = np.array([4,1,-2,3])
b1 = a1
b2 = a2 - (np.dot(a2, b1)/np.dot(b1, b1)) * b1
b3 = a3 - (np.dot(a3, b1)/np.dot(b1, b1)) * b1 - (np.dot(a3, b2)/np.dot(b2, b2)) * b2
b4 = a4 - (np.dot(a4, b1)/np.dot(b1, b1)) * b1 - (np.dot(a4, b2)/np.dot(b2, b2)) * b2 - (np.dot(a4, b3)/np.dot(a4, b3)) * b3
b1 = b1 / np.linalg.norm(b1)
b2 = b2 / np.linalg.norm(b2)
b3 = b3 / np.linalg.norm(b3)
b4 = b4 / np.linalg.norm(b4)
np.max(b4)

0.8438105239546116

In [15]:
a = np.array([-2,0,3])
np.linalg.norm(a)

3.605551275463989

In [16]:
a = np.array([9,-12,0])
np.linalg.norm(a)

15.0

In [29]:
from sympy import Matrix
A = np.array([[1,-1,-1,3], [-2,1,7,2], [-2,0,12,10], [-3,2,8,-1]])
M = Matrix(A).rref()
print(M)
a1 = np.array([6,5,1,0])
a2 = np.array([5,8,0,1])
a3 = np.array([1,0,1,-1])
b1 = a1
b2 = a2 - (np.dot(a2, b1)/np.dot(b1, b1)) * b1
b3 = a3 - (np.dot(a3, b1)/np.dot(b1, b1)) * b1 - (np.dot(a3, b2)/np.dot(b2, b2)) * b2
print(np.linalg.norm(b3))

(Matrix([
[1, 0, -6, -5],
[0, 1, -5, -8],
[0, 0,  0,  0],
[0, 0,  0,  0]]), (0, 1))
0.9058632541913364


In [19]:
A = np.array([[1,0,2], [0,0,1], [1,1,1]])
q, r = np.linalg.qr(A)
print(q)
print(r)

[[-0.70710678  0.70710678  0.        ]
 [-0.          0.         -1.        ]
 [-0.70710678 -0.70710678  0.        ]]
[[-1.41421356 -0.70710678 -2.12132034]
 [ 0.         -0.70710678  0.70710678]
 [ 0.          0.         -1.        ]]


In [22]:
A = np.array([[3,1,-2], [1,1,1], [-1,2,4]])
q, r = np.linalg.qr(A)
print(r)
print(np.sum(r))

[[-3.31662479 -0.60302269  2.7136021 ]
 [ 0.         -2.3741027  -3.63773801]
 [ 0.          0.         -0.63500064]]
-7.852886724691756


In [24]:
A = np.array([[3,0,4], [0,1,0], [4,0,-3]])
w, v = np.linalg.eig(A)
print(w)
print(v)

[ 5. -5.  1.]
[[ 0.89442719 -0.4472136   0.        ]
 [ 0.          0.          1.        ]
 [ 0.4472136   0.89442719  0.        ]]


In [25]:
A = np.array([[0,2,5], [2,-3,-2], [5,-2,0]])
w, v = np.linalg.eig(A)
print(w)
print(v)

[-7.  5. -1.]
[[ 5.77350269e-01 -7.07106781e-01 -4.08248290e-01]
 [-5.77350269e-01  2.85835702e-17 -8.16496581e-01]
 [-5.77350269e-01 -7.07106781e-01  4.08248290e-01]]
